import 'package:flutter/material.dart';

const Color primaryColor = Color(0xFF6CC7A5);
const Color primaryColorLight = Color(0xFFbdf7e1);
const Color primaryColorDark = Color(0xFF6aa58f);
const Color secondaryColor = Color(0xFF095688);
const Color secondaryColorLight = Color(0xFFe3ecf2);
const Color textColorWhite = Color(0xFFffffff);
const Color textColorBlack = Color(0xFF000000);
const Color textColorGrey = Color(0xFF535353);
const Color textColorLightGrey = Color(0xFFb6b6b6);
const Color textColorRed = Color(0xFFfe1c1c);
const Color textColorRedDark = Color(0xFFC70039 );
const Color textColorGreen = Color(0xFF0dcb00);
const Color textColorDarkBlue = Color(0xFF003049);
const Color textColorLightBlue = Color(0xFF376c87);
const Color shadowColor = Color(0xFF535353);
const Color widgetGreyColor = Color(0xFF535353);
const Color widgetLightGreyColor = Color(0xFFb6b6b6);
const Color lightShadowColor = Color(0xFFE0E0E0);
const Color widgetLighterGreyColor = Color(0xFFf1f1f1);
const Color widgetBgColor = Color(0xFFffffff);
const Color transparent = Color(0x00000000);